project:
  type: website
  output-dir: docs

website:
  title: "Evelia Coss"
  back-to-top-navigation: true #boton Back to the top
  
  navbar:
    search: true
    right:
      - text: "Home" 
        href: index.qmd
      - about.qmd
      - publications/index.qmd #publications.qmd
      - text: "Talks and Tutorials"
        href: tutorials.qmd
      - text: "Videos"
        href: videos.qmd      
      - text: "Projects" 
        href: projects.qmd      
      - icon: github
        href: https://github.com/EveliaCossNav/Website_EveCoss

  sidebar:
    - title: "Talks and Tutorials"
      style: "docked"
      background: light
      border: true
      contents:
        - tutorials.qmd
        - tutorial-1.qmd
        - tutorial-2.qmd

    - title: "Projects"
      style: "docked"
      background: light
      border: true
      contents:
        - projects.qmd  

  # Parte inferior de la pagina web
  page-footer: 
    border: false
    left: "Published with [Quarto](https://quarto.org/docs/websites) v1.3.450, by Evelia Coss. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right: 
      - icon: github
        href: https://github.com/EveliaCoss/

format:
  html:
    theme:
      light: pulse
      dark: darkly
    css: styles.css
    toc: true

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: false
  
filters:
  - reveal-logo # install quarto add royfrancis/quarto-reveal-logo
  - lightbox # install quarto add quarto-ext/lightbox
  - fontawesome # install quarto add quarto-ext/fontawesome


schedule_message:
colors:
  primary: "#95b540"
  secondary: "#BDD775"
  tertiary: "#E9F2D1"
  
editor: visual

